### ISSUE TITLE
Crash on AppInit | API <= 22

### ISSUE THREAD

**Issue by dreamsyntax** [berdosi/HeartBeat#24]
## Stacktrace
```Java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.berdosi.app.heartbeat, PID: 3475
    java.lang.NoSuchMethodError: No super method onRequestPermissionsResult(I[Ljava/lang/String;[I)V in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
        at eu.berdosi.app.heartbeat.MainActivity.onRequestPermissionsResult(MainActivity.java:133)
        at androidx.core.app.ActivityCompat$1.run(ActivityCompat.java:519)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
## Cause
Note: I verified this issue also happens in v1.2, so this is not caused by v1.2.1.
* onRequestPermissionsResult only is supported in API 23, this is when Android introduced individual permissions enable/disable

## Solutions
1. minSDK can be bumped up to API 23 (Android Marshmallow 6.0). 
-- According to Google stats as of Aug 18, 2021: Android 6.0+ holds 84.9% marketshare.
-- Users on Android 5.0 and 5.1 would no longer be able to install the app (it would crash for them currently anyway).
2. Remove `super.onRequestPermissionsResult(requestCode, permissions, grantResults)`, this is a callback stub anyway

**Comment by dreamsyntax** [comment]
Upon further investigation it seems the app will crash on measurement completion on API 22-
```Java
2021-08-18 14:19:35.186 4649-4649/eu.berdosi.app.heartbeat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.berdosi.app.heartbeat, PID: 4649
    java.lang.IllegalArgumentException: Unknown pattern character 'X'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:314)
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:303)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:356)
        at eu.berdosi.app.heartbeat.OutputAnalyzer$1.onFinish(OutputAnalyzer.java:173)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
Breaking on `<string name="dateFormatGranular">yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX</string>`
```Java                            
new SimpleDateFormat(
          activity.getString(R.string.dateFormatGranular),
          Locale.getDefault()
          ).format(value.timestamp);
```

I suggest dropping API 5.0/5.1 support.

**Comment by berdosi** [comment]
Thanks for the fix and details!
